version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=Cloud Image API
      - ENVIRONMENT=production
      - DEBUG=false
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DATABASE_URL=${DATABASE_URL}
      - R2_ENDPOINT_URL=${R2_ENDPOINT_URL}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
      - REDIS_URL=redis://redis:6379/0
      - REDIS_CACHE_EXPIRY=86400
      - MAX_IMAGE_SIZE=10485760
      - ALLOWED_EXTENSIONS=["jpg", "jpeg", "png", "gif", "webp"]
    depends_on:
      - redis
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --appendonly yes

volumes:
  redis-data:
