name: cloud-image-api
region: fra
services:
  - name: api
    github:
      branch: main
      deploy_on_push: true
      repo: mdhamed238/cloud_image_api
    build_command: pip install -r requirements.txt && alembic upgrade head
    run_command: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envs:
      - key: APP_NAME
        value: "Cloud Image API"
      - key: ENVIRONMENT
        value: "production"
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: R2_ENDPOINT_URL
        scope: RUN_TIME
        type: SECRET
      - key: R2_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: R2_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: R2_BUCKET_NAME
        scope: RUN_TIME
        type: SECRET
      - key: R2_PUBLIC_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_CACHE_EXPIRY
        value: "86400"
      - key: MAX_IMAGE_SIZE
        value: "10485760"
      - key: ALLOWED_EXTENSIONS
        value: '["jpg", "jpeg", "png", "gif", "webp"]'
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "15"
